dist: trusty
sudo: false
language: python

python:
  - "2.7"
  - "3.3"
  - "3.5"
  - "3.5"
  - "3.6"
  - "nightly"

# command to install dependencies
install:
  - "pip install -r requirements-test.txt"

# command to run tests
script:
  - "py.test"
