language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
before_install:
  - uname -a
  - lsb_release -a
  - python --version
  - virtualenv --version
  - pip --version
install:
  - pip install pipx
  - pipx install poetry
  - poetry install
script:
  - py.test -v tests
notifications:
  email:
    on_success: never
on_failure: always
